export const data = {
    name: "root",
    isFolder:true,
    items:[
        {
            name:"public",
            isFolder:true,
            items:[
               {
                name:"index.html",
                isFolder:false,
               } 
            ]
        },
        {
            name:"src",
            isFolder:true,
            items:[
                {
                    name:"components",
                    isFolder:true,
                    items:[
                        {
                            name:"Explorer.js",
                            isFolder:false,
                        }
                    ]
                  },
                  {
                    name:"constant",
                    isFolder:true,
                    items:[
                        {
                            name:"Data.js",
                            isFolder:false,
                        }
                    ]
                  },
                {
                    name:"App.js",
                    isFolder:false,
                },
                {
                    name:"index.js",
                    isFolder:false,
                },
                {
                    name:"App.css",
                    isFolder:false,
                },
                {
                    name:"index.css",
                    isFolder:false,
                },
                {
                    name:"App.test.js",
                    isFolder:false,
                },
            
            ]
        },
        {
            name:".gitignore",
            isFolder:false,
        },
        {
            name:"package-lock.json",
            isFolder:false,
        },
        {
            name:"package.json",
            isFolder:false,
        },
        {
            name:"README.md",
            isFolder:false,
        },
    ]
}